<a href="https://colab.research.google.com/github/sachin-rastogi/workshops/blob/master/PyTorch/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
__author__="Sachin Rastogi"

Import Libraries

In [ ]:
import torch
import numpy as np
from IPython.display import display, Math, Latex

In [ ]:
torch.__version__

'1.6.0+cu101'

In [ ]:
# Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor,
# e.g. dtype, unless new values are provided by user

x = torch.ones(5, 3, dtype=torch.double)      # Changing an existing tensor, new_* methods take in sizes
print(x)

y = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.6264, -0.7392, -1.5767],
        [-1.8425,  0.3698,  0.4737],
        [-1.0417, -0.4686,  0.3047],
        [-0.6594,  1.7173, -1.0871],
        [-0.2720,  1.5802,  0.2829]])


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print("\n")
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)


In case you do not see above output as follows  
```
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], device='cuda:0', dtype=torch.float64)


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)

```
Goto Runtime -> change runtime type -> choose Hardware accelerator
as GPU  

And Re-run all above commands.



